# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pLists(object):
    def setupUi(self, pLists):
        pLists.setObjectName("pLists")
        pLists.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(pLists)
        self.centralwidget.setObjectName("centralwidget")
        pLists.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pLists)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        pLists.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pLists)
        self.statusbar.setObjectName("statusbar")
        pLists.setStatusBar(self.statusbar)
        self.menu_open = QtWidgets.QAction(pLists)
        self.menu_open.setObjectName("menu_open")
        self.menu_close = QtWidgets.QAction(pLists)
        self.menu_close.setObjectName("menu_close")
        self.menu_exit = QtWidgets.QAction(pLists)
        self.menu_exit.setObjectName("menu_exit")
        self.menu.addAction(self.menu_open)
        self.menu.addAction(self.menu_close)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_exit)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(pLists)
        QtCore.QMetaObject.connectSlotsByName(pLists)

    def retranslateUi(self, pLists):
        _translate = QtCore.QCoreApplication.translate
        pLists.setWindowTitle(_translate("pLists", "Путевые листы"))
        self.menu.setTitle(_translate("pLists", "Файл"))
        self.menu_open.setText(_translate("pLists", "Открыть"))
        self.menu_close.setText(_translate("pLists", "Закрыть"))
        self.menu_exit.setText(_translate("pLists", "Выход"))
