# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ruriko(object):
    def setupUi(self, Ruriko):
        Ruriko.setObjectName("Ruriko")
        Ruriko.resize(800, 600)
        Ruriko.setMinimumSize(QtCore.QSize(800, 600))
        Ruriko.setMaximumSize(QtCore.QSize(16777215, 1210))
        self.label = QtWidgets.QLabel(Ruriko)
        self.label.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.label.setMaximumSize(QtCore.QSize(900, 1200))
        self.label.setObjectName("label")
        self.labelHair = QtWidgets.QLabel(Ruriko)
        self.labelHair.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelHair.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelHair.setObjectName("labelHair")
        self.labelFace = QtWidgets.QLabel(Ruriko)
        self.labelFace.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelFace.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelFace.setObjectName("labelFace")
        self.labelPiersing = QtWidgets.QLabel(Ruriko)
        self.labelPiersing.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelPiersing.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelPiersing.setObjectName("labelPiersing")
        self.labelMask = QtWidgets.QLabel(Ruriko)
        self.labelMask.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelMask.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelMask.setObjectName("labelMask")
        self.labelUnderwearBottom = QtWidgets.QLabel(Ruriko)
        self.labelUnderwearBottom.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelUnderwearBottom.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelUnderwearBottom.setObjectName("labelUnderwearBottom")
        self.labelUnderwearUpper = QtWidgets.QLabel(Ruriko)
        self.labelUnderwearUpper.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelUnderwearUpper.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelUnderwearUpper.setObjectName("labelUnderwearUpper")
        self.labelLegs = QtWidgets.QLabel(Ruriko)
        self.labelLegs.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelLegs.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelLegs.setObjectName("labelLegs")
        self.labelShoes = QtWidgets.QLabel(Ruriko)
        self.labelShoes.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelShoes.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelShoes.setObjectName("labelShoes")
        self.labelUpper = QtWidgets.QLabel(Ruriko)
        self.labelUpper.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelUpper.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelUpper.setObjectName("labelUpper")
        self.labelBottom = QtWidgets.QLabel(Ruriko)
        self.labelBottom.setGeometry(QtCore.QRect(320, 0, 900, 1200))
        self.labelBottom.setMaximumSize(QtCore.QSize(900, 1200))
        self.labelBottom.setObjectName("labelBottom")
        self.label.raise_()
        self.labelFace.raise_()
        self.labelHair.raise_()
        self.labelPiersing.raise_()
        self.labelMask.raise_()
        self.labelUnderwearBottom.raise_()
        self.labelUnderwearUpper.raise_()
        self.labelLegs.raise_()
        self.labelShoes.raise_()
        self.labelUpper.raise_()
        self.labelBottom.raise_()

        self.retranslateUi(Ruriko)
        QtCore.QMetaObject.connectSlotsByName(Ruriko)

    def retranslateUi(self, Ruriko):
        _translate = QtCore.QCoreApplication.translate
        Ruriko.setWindowTitle(_translate("Ruriko", "Form"))
        self.label.setText(_translate("Ruriko", "TextLabel"))
        self.labelHair.setText(_translate("Ruriko", "Hair"))
        self.labelFace.setText(_translate("Ruriko", "TextLabel"))
        self.labelPiersing.setText(_translate("Ruriko", "Hair"))
        self.labelMask.setText(_translate("Ruriko", "Hair"))
        self.labelUnderwearBottom.setText(_translate("Ruriko", "Hair"))
        self.labelUnderwearUpper.setText(_translate("Ruriko", "Hair"))
        self.labelLegs.setText(_translate("Ruriko", "Hair"))
        self.labelShoes.setText(_translate("Ruriko", "Hair"))
        self.labelUpper.setText(_translate("Ruriko", "Hair"))
        self.labelBottom.setText(_translate("Ruriko", "Hair"))
