# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 70, 781, 451))
        self.tableView.setObjectName("tableView")
        self.button_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.button_refresh.setGeometry(QtCore.QRect(390, 10, 150, 50))
        self.button_refresh.setMinimumSize(QtCore.QSize(150, 50))
        self.button_refresh.setMaximumSize(QtCore.QSize(150, 50))
        self.button_refresh.setObjectName("button_refresh")
        self.label_data = QtWidgets.QLabel(self.centralwidget)
        self.label_data.setGeometry(QtCore.QRect(10, 10, 80, 20))
        self.label_data.setMinimumSize(QtCore.QSize(80, 20))
        self.label_data.setMaximumSize(QtCore.QSize(80, 20))
        self.label_data.setObjectName("label_data")
        self.button_new = QtWidgets.QPushButton(self.centralwidget)
        self.button_new.setGeometry(QtCore.QRect(630, 10, 150, 50))
        self.button_new.setMinimumSize(QtCore.QSize(150, 50))
        self.button_new.setMaximumSize(QtCore.QSize(150, 50))
        self.button_new.setObjectName("button_new")
        self.label_user = QtWidgets.QLabel(self.centralwidget)
        self.label_user.setGeometry(QtCore.QRect(10, 40, 150, 20))
        self.label_user.setMinimumSize(QtCore.QSize(150, 20))
        self.label_user.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_user.setFont(font)
        self.label_user.setObjectName("label_user")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_refresh.setText(_translate("MainWindow", "Обновить"))
        self.label_data.setText(_translate("MainWindow", "Дата"))
        self.button_new.setText(_translate("MainWindow", "Создать"))
        self.label_user.setText(_translate("MainWindow", "Пользователь"))
