# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_server_start = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_server_start.setGeometry(QtCore.QRect(10, 20, 75, 20))
        self.pushButton_server_start.setObjectName("pushButton_server_start")
        self.pushButton_file_open = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_file_open.setEnabled(False)
        self.pushButton_file_open.setGeometry(QtCore.QRect(10, 50, 75, 20))
        self.pushButton_file_open.setObjectName("pushButton_file_open")
        self.pushButton_find = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_find.setEnabled(False)
        self.pushButton_find.setGeometry(QtCore.QRect(540, 20, 75, 20))
        self.pushButton_find.setObjectName("pushButton_find")
        self.label_status_connect = QtWidgets.QLabel(self.centralwidget)
        self.label_status_connect.setEnabled(True)
        self.label_status_connect.setGeometry(QtCore.QRect(110, 20, 60, 20))
        self.label_status_connect.setObjectName("label_status_connect")
        self.label_filename = QtWidgets.QLabel(self.centralwidget)
        self.label_filename.setGeometry(QtCore.QRect(110, 50, 501, 20))
        self.label_filename.setObjectName("label_filename")
        self.lineEdit_find = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_find.setEnabled(False)
        self.lineEdit_find.setGeometry(QtCore.QRect(410, 20, 113, 20))
        self.lineEdit_find.setObjectName("lineEdit_find")
        self.label_find = QtWidgets.QLabel(self.centralwidget)
        self.label_find.setGeometry(QtCore.QRect(320, 20, 47, 20))
        self.label_find.setObjectName("label_find")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setEnabled(False)
        self.textEdit.setGeometry(QtCore.QRect(10, 90, 771, 441))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_detail = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_detail.setEnabled(False)
        self.pushButton_detail.setGeometry(QtCore.QRect(630, 20, 75, 23))
        self.pushButton_detail.setObjectName("pushButton_detail")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_server_start.setText(_translate("MainWindow", "Start server"))
        self.pushButton_file_open.setText(_translate("MainWindow", "Open file"))
        self.pushButton_find.setText(_translate("MainWindow", "Find"))
        self.label_status_connect.setText(_translate("MainWindow", "Status"))
        self.label_filename.setText(_translate("MainWindow", "filename"))
        self.label_find.setText(_translate("MainWindow", "Find in file"))
        self.pushButton_detail.setText(_translate("MainWindow", "Detail"))
