# Generated by Django 4.2.3 on 2023-08-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanview', '0003_filial_hardware_filial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filial',
            name='location',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
