# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Game_B(object):
    def setupUi(self, Game_B):
        Game_B.setObjectName("Game_B")
        Game_B.resize(800, 600)
        Game_B.setMinimumSize(QtCore.QSize(800, 600))
        Game_B.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(Game_B)
        self.centralwidget.setObjectName("centralwidget")
        Game_B.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Game_B)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Game_B.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Game_B)
        self.statusbar.setObjectName("statusbar")
        Game_B.setStatusBar(self.statusbar)

        self.retranslateUi(Game_B)
        QtCore.QMetaObject.connectSlotsByName(Game_B)

    def retranslateUi(self, Game_B):
        _translate = QtCore.QCoreApplication.translate
        Game_B.setWindowTitle(_translate("Game_B", "Game_B"))
