# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 147)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_path_to_dir = QtWidgets.QPushButton(self.centralwidget)
        self.button_path_to_dir.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.button_path_to_dir.setObjectName("button_path_to_dir")
        self.line_edit_src = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_src.setGeometry(QtCore.QRect(110, 70, 113, 20))
        self.line_edit_src.setObjectName("line_edit_src")
        self.line_edit_dst = QtWidgets.QLineEdit(self.centralwidget)
        self.line_edit_dst.setGeometry(QtCore.QRect(270, 70, 113, 20))
        self.line_edit_dst.setObjectName("line_edit_dst")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 491, 23))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 70, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 70, 21, 16))
        self.label_3.setObjectName("label_3")
        self.button_ok = QtWidgets.QPushButton(self.centralwidget)
        self.button_ok.setGeometry(QtCore.QRect(430, 70, 75, 23))
        self.button_ok.setObjectName("button_ok")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_path_to_dir.setText(_translate("MainWindow", "Обзор"))
        self.label_2.setText(_translate("MainWindow", "C"))
        self.label_3.setText(_translate("MainWindow", "на"))
        self.button_ok.setText(_translate("MainWindow", "OK"))
